# Icons

- name: "Arrow - Right"
  path: "/images/icons/icon-arrow-right-grey.svg"
- name: "Arrow - Left"
  path: "/images/icons/icon-arrow-left-grey.svg"
- name: "Arrow - Up"
  path: "/images/icons/icon-arrow-up-grey.svg"
- name: "Arrow - Down"
  path: "/images/icons/icon-arrow-down-grey.svg"
- name: "Calendar"
  path: "/images/icons/icon-calendar-grey.svg"
- name: "Caret"
  path: "/images/icons/icon-caret-grey.svg"
- name: "Close"
  path: "/images/icons/icon-close-grey.svg"
- name: "Download"
  path: "/images/icons/icon-download-grey.svg"
- name: "Expand"
  path: "/images/icons/icon-expand-grey.svg"
- name: "Export"
  path: "/images/icons/icon-export-grey.svg"
- name: "External"
  path: "/images/icons/icon-external-grey.svg"
- name: "Info"
  path: "/images/icons/icon-info-grey.svg"
- name: "Link"
  path: "/images/icons/icon-link-grey.svg"
- name: "Markdown"
  path: "/images/icons/icon-markdown-grey.svg"
- name: "Edit"
  path: "/images/icons/icon-edit-grey.svg"
- name: "Plus Open"
  path: "/images/icons/icon-plus-open-grey.svg"
- name: "Refresh"
  path: "/images/icons/icon-refresh-grey.svg"
- name: "Search"
  path: "/images/icons/icon-search-grey.svg"
- name: "Share"
  path: "/images/icons/icon-share-grey.svg"
- name: "Trash"
  path: "/images/icons/icon-trash-grey.svg"
- name: "Docs"
  path: "/images/icons/icon-docs-grey.svg"
- name: "Check"
  path: "/images/icons/icon-check-grey.svg"
- name: "Sort - Unsorted"
  path: "/images/icons/icon-sort-unsorted-grey.svg"
- name: "Sort - Up"
  path: "/images/icons/icon-sort-up-grey.svg"
- name: "Sort - Down"
  path: "/images/icons/icon-sort-down-grey.svg"
- name: "API"
  path: "/images/icons/icon-api-grey.svg"
- name: "Attachment"
  path: "/images/icons/icon-attachment-grey.svg"
- name: "Back"
  path: "/images/icons/icon-back-button-grey.svg"
- name: "Checkmark Circled"
  path: "/images/icons/icon-checkmark-circled-grey.svg"
- name: "Cloud"
  path: "/images/icons/icon-cloud-grey.svg"
- name: "Email"
  path: "/images/icons/icon-email-grey.svg"
- name: "Phone"
  path: "/images/icons/icon-phone-grey.svg"
- name: "Copy"
  path: "/images/icons/icon-copy-grey.svg"
- name: "Error"
  path: "/images/icons/icon-error-grey.svg"
- name: "Filter"
  path: "/images/icons/icon-filter-grey.svg"
- name: "Hide"
  path: "/images/icons/icon-hide-grey.svg"
- name: "Home"
  path: "/images/icons/icon-home-grey.svg"
- name: "Help Info"
  path: "/images/icons/icon-info-help-grey.svg"
- name: "Beta"
  path: "/images/icons/icon-beta-grey.svg"
- name: "Save"
  path: "/images/icons/icon-save-grey.svg"
- name: "Read Only"
  path: "/images/icons/icon-read-only-grey.svg"
- name: "Secure"
  path: "/images/icons/icon-secure-grey.svg"
- name: "Caret 2"
  path: "/images/icons/icon-caret-2-grey.svg"
- name: "Log Out"
  path: "/images/icons/icon-logout-grey.svg"
- name: "Gear"
  path: "/images/icons/icon-gear-grey.svg"
- name: "Folder"
  path: "/images/icons/icon-folder-grey.svg"
- name: "Key"
  path: "/images/icons/icon-key-grey.svg"
- name: "Book"
  path: "/images/icons/icon-book-grey.svg"
- name: "Brush"
  path: "/images/icons/icon-brush-grey.svg"
- name: "Cloud 2"
  path: "/images/icons/icon-cloud-2-grey.svg"
- name: "User"
  path: "/images/icons/icon-user-grey.svg"
- name: "List View"
  path: "/images/icons/icon-list-view-grey.svg"
- name: "Card View"
  path: "/images/icons/icon-card-view-grey.svg"
- name: "Ticket"
  path: "/images/icons/icon-ticket-grey.svg"
- name: "Feedback"
  path: "/images/icons/icon-feedback-grey.svg"
- name: "Admin"
  path: "/images/icons/icon-admin-grey.svg"
- name: "Lock"
  path: "/images/icons/icon-lock-grey.svg"
